name: whatsapp_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #firebase related
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.8.3
  firebase_storage: ^11.2.5

  # working with images
  image_picker: ^1.0.1

  jiffy: ^6.2.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  color: '#ffffff'
  image: assets/icons/whatsapp.png
  android: true
  ios: true

flutter:
  uses-material-design: true
